# Auto-generated by IDE. Any changes made by user will be lost!
BASEDIR =  $$quote($$_PRO_FILE_PWD_)

device {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/telegram/tl/StreamingUtils.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBool.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolFalse.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolTrue.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLContext.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLGzipObject.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLIntVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLLongVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLMethod.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLObject.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLStringVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLVector.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/telegram/tl/StreamingUtils.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBool.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolFalse.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolTrue.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLContext.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLGzipObject.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLIntVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLLongVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLMethod.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLObject.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLStringVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLVector.hpp)
    }

    CONFIG(release, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/telegram/tl/StreamingUtils.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBool.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolFalse.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolTrue.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLContext.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLGzipObject.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLIntVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLLongVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLMethod.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLObject.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLStringVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLVector.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/telegram/tl/StreamingUtils.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBool.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolFalse.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolTrue.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLContext.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLGzipObject.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLIntVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLLongVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLMethod.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLObject.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLStringVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLVector.hpp)
    }
}

simulator {
    CONFIG(debug, debug|release) {
        SOURCES +=  $$quote($$BASEDIR/src/telegram/tl/StreamingUtils.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBool.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolFalse.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolTrue.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLContext.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLGzipObject.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLIntVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLLongVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLMethod.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLObject.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLStringVector.cpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLVector.cpp)

        HEADERS +=  $$quote($$BASEDIR/src/telegram/tl/StreamingUtils.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBool.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolFalse.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLBoolTrue.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLContext.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLGzipObject.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLIntVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLLongVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLMethod.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLObject.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLStringVector.hpp) \
                 $$quote($$BASEDIR/src/telegram/tl/TLVector.hpp)
    }
}

INCLUDEPATH +=  $$quote($$BASEDIR/src/telegram/tl)

CONFIG += precompile_header

PRECOMPILED_HEADER =  $$quote($$BASEDIR/precompiled.h)

lupdate_inclusion {
    SOURCES +=  $$quote($$BASEDIR/../src/*.c) \
             $$quote($$BASEDIR/../src/*.c++) \
             $$quote($$BASEDIR/../src/*.cc) \
             $$quote($$BASEDIR/../src/*.cpp) \
             $$quote($$BASEDIR/../src/*.cxx) \
             $$quote($$BASEDIR/../src/telegram/*.c) \
             $$quote($$BASEDIR/../src/telegram/*.c++) \
             $$quote($$BASEDIR/../src/telegram/*.cc) \
             $$quote($$BASEDIR/../src/telegram/*.cpp) \
             $$quote($$BASEDIR/../src/telegram/*.cxx) \
             $$quote($$BASEDIR/../src/telegram/tl/*.c) \
             $$quote($$BASEDIR/../src/telegram/tl/*.c++) \
             $$quote($$BASEDIR/../src/telegram/tl/*.cc) \
             $$quote($$BASEDIR/../src/telegram/tl/*.cpp) \
             $$quote($$BASEDIR/../src/telegram/tl/*.cxx)

    HEADERS +=  $$quote($$BASEDIR/../src/*.h) \
             $$quote($$BASEDIR/../src/*.h++) \
             $$quote($$BASEDIR/../src/*.hh) \
             $$quote($$BASEDIR/../src/*.hpp) \
             $$quote($$BASEDIR/../src/*.hxx)
}

TRANSLATIONS =  $$quote($${TARGET}.ts)
